### ISSUE TITLE
Caching when font not found

### ISSUE THREAD

**Issue by Harbs** [diverted247/txtjs#12]
When a font is not found on a server, a 404 response is returned. In this case, the response should be rejected. Instead, the response is blindly cached as the font, and a subsequent attempt to load a valid font fails because the (corrupt) cache already exists.

**Comment by diverted247** [comment]
Should be a straightforward fix.

How would you prefer the system respond?

- Throw "Font Not Found"
- Swap instance to default font
- ??

**Comment by Harbs** [comment]
My issue was more regarding the caching than the actual response.

Either of your two responses are valid. My main point is that the font should not be cached when it's not found so a subsequent load where it is valid will work correctly.

Regarding your question, I think a switch would probably be the best way to go. Flash defaults to the system default font, but there are times where I would have liked to flag that the font is the incorrect one.

**Comment by diverted247** [comment]
I understand this now. When a 404 is received, the data is pushed into a
font and cached.

Thinking we should:

1. Not cache the 404,
2. Stop rendering to prevent error.
3. Call text.error callback

Thoughts and Thanks

**Comment by Harbs** [comment]
Sounds like a plan.

It might be nice to have a renderDefaultOnError (or similar) property where instead of 2, it would render using the default font (Arial?) instead. The error callback should be called in all cases though.

**Comment by diverted247** [comment]
All this is implemented in 0.9.4+
