### ISSUE TITLE
Special unicode characters

### ISSUE THREAD

**Issue by vcostin** [diverted247/txtjs#13]
First of all thanks for this amassing library it helps a lot with text manipulation and rendering on canvas element.
Currently I'm rendering some content that has some special characters that contain some behavior, as I understand those type of characters are used in text formatting. To be specific I talk about:
- '\u200B' - zero width space
- '\u2008' - punctuation space
- ... I'm sure there are more, sorry to not researching to provide a full list.
  For now I'm replacing them with a space character as a work around.

```
var contentText = "continuous\u200Banotertext\u2028-mess"; 
contentText = contentText.replace(/\u200B/g, ' ');
contentText = contentText.replace(/\u2028/g, "\n");
```

**Comment by diverted247** [comment]
Font glyphs in txt are organized by characterCode (unicode limitation) and passed in via fonts in .txt files. You can add glyphs at runtime... txt.FontLoader.fonts... or add them into the .txt file to support these cases. Ideally you could swap unicode for the charactercode and it should render correctly.
