### ISSUE TITLE
fillColor not updating Text instance color

### ISSUE THREAD

**Issue by h3ph4est7s** [diverted247/txtjs#14]
Greetings,
i have tried to update the text color from mouseover mouseout events like below:

<pre>
this._onMouseOverOutBtn = function (event) {
        for (var child in event.currentTarget.children) {
            if (event.currentTarget.children[child] instanceof txt.Text) {
                if (event.type === "mouseover") {
                    /* Change color on mouse over */
                    event.currentTarget.children[child].fillColor="#fdc008";
                } else if (event.type == "mouseout") {
                    /* Change color on mouse out */
                    event.currentTarget.children[child].fillColor = "#ffffff";
                }
            }
        }
    };
</pre>

but the color is not changing and i have assigned a ticker - update routine  to auto update the stage.

**Comment by Harbs** [comment]
Keep in mind that I'm still kind of new to txtjs, so I might not be qualified to answer this and take this for what it's worth.

I don't know what you are doing in your ticker, but AFAIK, txtjs has no concept of marking text dirty. When you need to update text, you need to call layout() which redraws everything related to the text.

You probably want to keep track of whether you need to call layout() in your ticker.

**Comment by diverted247** [comment]
txt uses the easeljs drawing api to render text on a single pass within
layout(). It is very lazy so if you change properties, you must call
layout() to get them to show. The children within any Text control are just
displayobjects and are easily manipulated with easeljs apis... move
characters/lines etc. But to change fill or stroke, these need a full
layout call.

Ted :)

**Comment by ppanos** [comment]
i have used the fontLoaded method to update text but i have pushed the envelope and patched the library to use cache after that i implemented my project to redraw the hole thing. Thank you for your answer!!!
