### ISSUE TITLE
Elements inside canvas appear in browser inpector.

### ISSUE THREAD

**Issue by tsambora** [diverted247/txtjs#16]
Is there anyway to prevent this from happening? Thanks before.

**Comment by diverted247** [comment]
The elements are created within the txt.Accessibility API here... https://github.com/diverted247/txtjs/blob/master/src/txt/Accessibility.ts

Simply remove code in the set() and update() methods.

Thinking it makes sense to add a property to manage this... txt.Accessibility.active = true (default) and to turn it all off...  txt.Accessibility.active = false

**Comment by tsambora** [comment]
So it is configurable then. Thank you for the instruction. And yes it would be really convenient if there's a configurable property for the accessibility.
