### ISSUE TITLE
SVGPathSeg is deprecated and will be removed in Chrome 48.

### ISSUE THREAD

**Issue by annalectsk** [diverted247/txtjs#17]
https://www.chromestatus.com/feature/5708851034718208

PathText isn't working anymore ("Uncaught TypeError: Cannot read property 'getItem' of undefined"). Any suggestions?

Thank you very much!

**Comment by antzhdanov** [comment]
+1 for this. Meanwhile, there's a polyfill for SVGPathSeg here: https://github.com/progers/pathseg

**Comment by annalectsk** [comment]
@antzhdanov thanks for the tip, now i can start using nw.js beta4 :-)

**Comment by diverted247** [comment]
I updated the txtjs site. It now uses the pathseg polyfill and all tests are passing. I will need some time to determine an appropriate change to this to avoid using the polyfill. Again it only applies to use of PathText and Chrome 48 removed the SVGPathSeg object and related methods in what I view as an overly aggressive transition from SVG1.1 to 2.0. The 2.0 draft is dated Sept 15, 2015 and they depricated in production on Jan 27, that seems rash but they did ship a polyfill that works well.
