### ISSUE TITLE
Text quality on window.devicePixelRatio == 1

### ISSUE THREAD

**Issue by antzhdanov** [diverted247/txtjs#18]
I use PathText to draw arc text and it looks good on HiDPI screens with DPR>=2, but looks quite fuzzy on window.devicePixelRatio == 1.

My code: 

``` javascript
var text = new txt.PathText({
    text: 'sample text',
    name: 'text',
    font: 'Trade-Gothic',
    mouseEnabled: false,
    tickEnabled: false,
    fillColor: color,
    align: txt.PathAlign.Center,
    size: 15,
    path: 'M ' + startArc.x / stage.scaleX + ' ' + startArc.y / stage.scaleY + ' A ' + r + ' ' + r + ', ' + ' 0 0 1 ' + endArc.x / stage.scaleX + ' ' + endArc.y / stage.scaleY
});
```

Is there anything I can do with it except avoiding setting stroke to it?
Thank you in advance.

<img width="135" alt="example" src="https://cloud.githubusercontent.com/assets/1424394/14289260/aaedc3cc-fb62-11e5-97f1-92478f6e5bda.png">

**Comment by diverted247** [comment]
Single density rendering has so few pixels that text will look fuzzy. Best way to support this is to 2x the canvas size and downscale. It will still be fuzzy but on higher density screens it will improve dramatically. Hope this helps, sorry for delay.
