### ISSUE TITLE
mandatory fonts?

### ISSUE THREAD

**Issue by santospro** [diverted247/txtjs#20]
Hi, I'm new textjs user. But, Why I can't use directly the web browser fonts? 
I saw the createjs docs about [Text](http://createjs.com/docs/easeljs/classes/Text.html) and they use the web fonts, why txtjs can't do it?

`var text = new createjs.Text("Hello World", "20px Arial", "#ff7700");`

Thanks!

**Comment by diverted247** [comment]
Almost a year late but...

TXT uses glyphs extracted from SVG Fonts. These paths are enable vector rendering and positioning independent of the browser text layout engine. As txt knows the font baseline and kerning, ligatures, etc, it can layout text very accurately. When txt was created JS was unable to read binary webfont files and extract the proper details within them. Today that is possible but you will need a library to translate webfonts to the internal font data representation. Txt has tools to generate fonts from existing licensed ttf or otf files.
