### ISSUE TITLE
txt.js not working ?

### ISSUE THREAD

**Issue by alphakanal** [diverted247/txtjs#21]
Hi,
I'm new to txt.js and totally new to GitHub.
I've downloaded the ZIP. And try to open ( with Edge/Firefox ) i.e. PathText/text.html the canvas remains blank - no fonts are shown. This happens local and online ( uploaded all folders ). 

Due to the fact i'm new to the whole thing - what i'm doing wrong?
Thanks in advance for any advice :)
Robert

**Comment by diverted247** [comment]
New build is working perfectly, as was prior. This is likely due to path to fonts folder. This defaults to look in /fonts/ for any needed fonts. So relative paths would break.

**Comment by alphakanal** [comment]
Hi Ted!

Thank you for this Update!:) Maybe it solves my actual problems:

 

Some fonts aren't shown in the canvas although they are in the font-folder.

 

Gesendet: Donnerstag, 27. April 2017 um 15:32 Uhr
Von: "Ted Patrick" <notifications@github.com>
An: diverted247/txtjs <txtjs@noreply.github.com>
Cc: Robert <recker71@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [diverted247/txtjs] txt.js not working ? (#21)


New build is working perfectly, as was prior. This is likely due to path to fonts folder. This defaults to look in /fonts/ for any needed fonts. So relative paths would break.
