### ISSUE TITLE
Error with Font-Export Scripts

### ISSUE THREAD

**Issue by alphakanal** [diverted247/txtjs#22]
When trying to run main.py i got following Error:

File "MyPath:\main.py", line 8, in module from bs4 import BeautifulSoup
Imoprt Error: No module called bs4

I'm using WIN7 - I have no glue how to solve this ... i'm a total coding idiot

**Comment by diverted247** [comment]
I appended data into Readme:

pip install BeautifulSoup4
pip install lxml

These should address the font generation issues.
