### ISSUE TITLE
Obtain path data for text without rendering to canvas element?

### ISSUE THREAD

**Issue by rapodaca** [diverted247/txtjs#23]
I'd like to extract path data for text without rendering to canvas. Instead, I'd like to use the path in SVG.

I tried inspecting the object created by txt.CharacterText to see what I could do, but using this:

```javascript
var text = new txt.CharacterText( { 
    text:'The fox jumped over the log.',
    font:'raleway',
    //align:txt.Align.TOP_RIGHT,
    tracking:-4,
    lineHeight:120,
    width:600,
    height:360,
    size:120,
    x:10,
    y:10
} );
```

gave the error: txt.js:1490 Uncaught TypeError: Cannot read property 'update' of null

I tried navigating the API documentation, but it didn't seem to have anything I could use.

**Comment by diverted247** [comment]
All glyph data is stred in the .txt font files. These are loaded via ajax when the font if first used. In your example the txt.FontLoader would attempt to load '/font/raleway.txt' from your domain/relative path... ( http://txtjs.com/font/raleway.txt ) and then render. 

You can get to the glyph data at runtime.

Open js console on this web page:
http://txtjs.com/examples/Text/text.html

Looks at these results in console:
txt.FontLoader.fonts
txt.FontLoader.fonts.raleway.glyphs
txt.FontLoader.fonts.raleway.glyphs[57].path

https://www.dropbox.com/s/yihv3mwgb87z52q/Screenshot%202017-05-15%2007.55.34.png?dl=0
