### ISSUE TITLE
Can txtjs be used with fabricjs? 

### ISSUE THREAD

**Issue by cksachdev** [diverted247/txtjs#24]
Could you please point me to documentation on the interfaces and dependencies with createjs. I would like to use txtjs with fabricjs. 
Is txtjs same is TLF(Text layout framework) in flash? 

Is there any other alternative to txtjs for rich text editing on html5 canvas?
@kangax @diverted247

**Comment by diverted247** [comment]
The workflow for txtjs in rendering is:

1. Take SVGPath of font chars to drawing api commands.
2. Layout characters using font metrics and adding glyph chars.
3. Text

I am not sure fabric has the same rendering model, it is likely similar but the differences would make this a hard port. As we already depend on createjs, we made txtjs render dependent on createjs.
