### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by cksachdev** [diverted247/txtjs#25]
![image](https://cloud.githubusercontent.com/assets/37770/26049060/45f69486-3977-11e7-9832-605225895905.png)

**Comment by diverted247** [comment]
You are using TSC -g installed at 1.8.10 but local build of tsc.gulp is at 1.4.1.0. I would suggest installing typescript 1.4.1.0 with -g flag.

npm install -g typescript@1.4.1

**Comment by cksachdev** [comment]
Thx. It worked.
