### ISSUE TITLE
Using Hindi langauge font Notosansdevanagari

### ISSUE THREAD

**Issue by cksachdev** [diverted247/txtjs#26]
I followed the instructions mentioned in tools/fontexport/README.
![image](https://cloud.githubusercontent.com/assets/37770/26053810/e07a3476-3987-11e7-89be-9adca5eaab97.png)

Note: You can ignore noto_sans_regular issue in screenshot. English language works fine. I am trying to use Hindi language with fonts generated using the tool.

**Comment by cksachdev** [comment]
I discovered "Rajdhani" font and tried input example, but still it renders the "*"
![image](https://cloud.githubusercontent.com/assets/37770/26054829/c19d9b98-398b-11e7-8445-ef40a2ce19fc.png)

**Comment by diverted247** [comment]
txtjs uses the results from 

this.text.charAt( i ) //obtain char at position
this.character.charCodeAt( 0 ) //obtain charCode of character

These 2 calls do no account for unicode support. Likely the font in use is highly unicode dependent and thus glyphs stores in the unicode range fail to load.

While it is possible to support unicode characters/fonts, it is not in txtjs today and likely will not be for some time without contribution. It would be a fairly major set of work as all aspects of fonts would need to be touched, from font extraction to font format to glyph lookup tables to storage. It is not impossible but it would be a ways out in dev.
